In [18]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [4]:
df["X"] = 0

In [5]:
df["X"]

0       0
1       0
2       0
3       0
4       0
       ..
1455    0
1456    0
1457    0
1458    0
1459    0
Name: X, Length: 1460, dtype: int64

In [6]:
df["X"] = list(range(0, 1460))

In [7]:
df.X

0          0
1          1
2          2
3          3
4          4
        ...
1455    1455
1456    1456
1457    1457
1458    1458
1459    1459
Name: X, Length: 1460, dtype: int64

In [8]:
df["Y"] = pd.Series(list(range(0, 1459)))

In [9]:
df.Y

0          0.0
1          1.0
2          2.0
3          3.0
4          4.0
         ...
1455    1455.0
1456    1456.0
1457    1457.0
1458    1458.0
1459       NaN
Name: Y, Length: 1460, dtype: float64

In [10]:
df["LotArea_sqm"] = df["LotArea"] * 0.092903

In [11]:
df[["LotArea_sqm", "LotArea"]]

      LotArea_sqm  LotArea
0      785.030350     8450
1      891.868800     9600
2     1045.158750    11250
3      887.223650     9550
4     1324.796780    14260
...           ...      ...
1455   735.513051     7917
1456  1223.997025    13175
1457   840.028926     9042
1458   902.738451     9717
1459   923.177111     9937

[1460 rows x 2 columns]

In [12]:
df[["LotArea_sqm", "LotArea"]].sort_values("LotArea_sqm")

       LotArea_sqm  LotArea
956     120.773900     1300
1039    137.217731     1477
614     138.518373     1491
489     141.769978     1526
1038    142.420299     1533
...            ...      ...
451    6573.909183    70761
706   10697.687547   115149
249   14771.577000   159000
335   15297.407980   164660
313   19996.906235   215245

[1460 rows x 2 columns]

In [16]:
def is_big(value):
    if value > 9000:
        return "Big"
    else:
        return "Small"
        
df["LotArea"].apply(is_big)

0       Small
1         Big
2         Big
3         Big
4         Big
        ...
1455    Small
1456      Big
1457      Big
1458      Big
1459      Big
Name: LotArea, Length: 1460, dtype: object

In [17]:
df["LotArea"].apply(lambda value: "Big" if value > 9000 else "Small")

0       Small
1         Big
2         Big
3         Big
4         Big
        ...
1455    Small
1456      Big
1457      Big
1458      Big
1459      Big
Name: LotArea, Length: 1460, dtype: object

In [21]:
df["Is_Big"] = np.where(df["LotArea"] > 9000, "Big", "Small")

In [22]:
df["Is_Big"]

0       Small
1         Big
2         Big
3         Big
4         Big
        ...
1455    Small
1456      Big
1457      Big
1458      Big
1459      Big
Name: Is_Big, Length: 1460, dtype: object

In [23]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice', 'X', 'Y', 'LotArea_sqm', 'Is_Big'],
      dtype='object')

In [24]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,X,Y,LotArea_sqm,Is_Big
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,2,2008,WD,Normal,208500,0,0.0,785.03035,Small
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,5,2007,WD,Normal,181500,1,1.0,891.86880,Big
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,9,2008,WD,Normal,223500,2,2.0,1045.15875,Big
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,2,2006,WD,Abnorml,140000,3,3.0,887.22365,Big
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,12,2008,WD,Normal,250000,4,4.0,1324.79678,Big

In [25]:
df.assign(
    LotArea_sqm = df["LotArea"] * 0.092903,
    z = 1,
    yy = 1
)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,YrSold,SaleType,SaleCondition,SalePrice,X,Y,LotArea_sqm,Is_Big,z,yy
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,2008,WD,Normal,208500,0,0.0,785.030350,Small,1,1
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,2007,WD,Normal,181500,1,1.0,891.868800,Big,1,1
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,2008,WD,Normal,223500,2,2.0,1045.158750,Big,1,1
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,2006,WD,Abnorml,140000,3,3.0,887.223650,Big,1,1
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,2008,WD,Normal,250000,4,4.0,1324.796780,Big,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,2007,WD,Normal,175000,1455,1455.0,735.513051,Small,1,1
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,2010,WD,Normal,210000,1456,1456.0,1223.997025,Big,1,1
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,2010,WD,Normal,266500,1457,1457.0,840.028926,Big,1,1
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,2010,WD,Normal,142125,1458,1458.0,902.738451,Big,1,1
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,2008,WD,Normal,147500,1459,NaN,923.177111,Big,1,1

In [26]:
data = {
    "MSSubClass": [20, 60, 70],
    "MSZoning": ["RL", "RM", "RL"],
    "LotArea": [8450, 9600, 11250],
    "Street": ["Pave", "Pave", "Grvl"],
    "Neighborhood": ["CollgCr", "Veenker", "Crawfor"],
    "SalePrice": [208500, 181500, 223500]
}
df = pd.DataFrame(data)

In [27]:
df

   MSSubClass MSZoning  LotArea Street Neighborhood  SalePrice
0          20       RL     8450   Pave      CollgCr     208500
1          60       RM     9600   Pave      Veenker     181500
2          70       RL    11250   Grvl      Crawfor     223500

In [28]:
new_house = {
    "MSSubClass": 20,
    "MSZoning": "RL",
    "LotArea": 10000,
    "Street": "Pave",
    "Neighborhood": "CollgCr",
    "SalePrice": 200000
}

In [31]:
df.loc[0] = new_house

In [32]:
df

    MSSubClass MSZoning  LotArea Street Neighborhood  SalePrice
0           20       RL    10000   Pave      CollgCr     200000
1           60       RM     9600   Pave      Veenker     181500
2           70       RL    11250   Grvl      Crawfor     223500
10          20       RL    10000   Pave      CollgCr     200000

In [33]:
df.shape

(4, 6)

In [41]:
 df.reset_index(drop=True, inplace=True)

In [42]:
df

   MSSubClass MSZoning  LotArea Street Neighborhood  SalePrice
0          20       RL    10000   Pave      CollgCr     200000
1          60       RM     9600   Pave      Veenker     181500
2          70       RL    11250   Grvl      Crawfor     223500
3          20       RL    10000   Pave      CollgCr     200000

In [43]:
df

   MSSubClass MSZoning  LotArea Street Neighborhood  SalePrice
0          20       RL    10000   Pave      CollgCr     200000
1          60       RM     9600   Pave      Veenker     181500
2          70       RL    11250   Grvl      Crawfor     223500
3          20       RL    10000   Pave      CollgCr     200000

In [44]:
df.drop(columns=["Street"])

   MSSubClass MSZoning  LotArea Neighborhood  SalePrice
0          20       RL    10000      CollgCr     200000
1          60       RM     9600      Veenker     181500
2          70       RL    11250      Crawfor     223500
3          20       RL    10000      CollgCr     200000

In [45]:
df

   MSSubClass MSZoning  LotArea Street Neighborhood  SalePrice
0          20       RL    10000   Pave      CollgCr     200000
1          60       RM     9600   Pave      Veenker     181500
2          70       RL    11250   Grvl      Crawfor     223500
3          20       RL    10000   Pave      CollgCr     200000

In [46]:
df.drop(columns=["Street"], inplace=True)

In [47]:
df

   MSSubClass MSZoning  LotArea Neighborhood  SalePrice
0          20       RL    10000      CollgCr     200000
1          60       RM     9600      Veenker     181500
2          70       RL    11250      Crawfor     223500
3          20       RL    10000      CollgCr     200000

In [49]:
df.drop(["MSSubClass"], axis=1)

  MSZoning  LotArea Neighborhood  SalePrice
0       RL    10000      CollgCr     200000
1       RM     9600      Veenker     181500
2       RL    11250      Crawfor     223500
3       RL    10000      CollgCr     200000

In [50]:
df

   MSSubClass MSZoning  LotArea Neighborhood  SalePrice
0          20       RL    10000      CollgCr     200000
1          60       RM     9600      Veenker     181500
2          70       RL    11250      Crawfor     223500
3          20       RL    10000      CollgCr     200000

In [51]:
df.drop([0], axis=0)

   MSSubClass MSZoning  LotArea Neighborhood  SalePrice
1          60       RM     9600      Veenker     181500
2          70       RL    11250      Crawfor     223500
3          20       RL    10000      CollgCr     200000

In [53]:
del df["LotArea"]

In [54]:
df

   MSSubClass MSZoning Neighborhood  SalePrice
0          20       RL      CollgCr     200000
1          60       RM      Veenker     181500
2          70       RL      Crawfor     223500
3          20       RL      CollgCr     200000

In [55]:
df.pop("SalePrice")

0    200000
1    181500
2    223500
3    200000
Name: SalePrice, dtype: int64